Vidly/Vidly/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vidly.Data;
using Vidly.Models;
using Vidly.ViewModel;

namespace Vidly.Controllers
{
    public class CustomersController : Controller
    {
        private readonly MovieRentDbContext _context;

        public CustomersController(MovieRentDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpGet]
        public ActionResult Create()
        {
            var membershipTypes = _context.MembershipTypes.ToList();
            var model = new CreateCustomerViewModel
            {
                MembershipTypes = membershipTypes
            };
            return View(model);
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateCustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Customers.Add(model.Customer);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }
            model.MembershipTypes = _context.MembershipTypes.ToList();
            return View(model);
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return NotFound();

            var viewModel = new CreateCustomerViewModel
            {
                Customer = customer,
                MembershipTypes = _context.MembershipTypes.ToList()
            };

            return View(viewModel);
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CreateCustomerViewModel model)
        {
            var customer = _context.Customers.FirstOrDefault(c => c.Id == model.Customer.Id);
            
            
                if (ModelState.IsValid)
                {
                    customer.Name = model.Customer.Name;
                    customer.BirthDate = model.Customer.BirthDate;
                    customer.IsSubscribedToNewsLetter = model.Customer.IsSubscribedToNewsLetter;
                    customer.MembershipTypeId = model.Customer.MembershipTypeId;

                    _context.SaveChanges();

                    return RedirectToAction(nameof(Index));
                }
            model.MembershipTypes = _context.MembershipTypes.ToList();
            return View(model);
        }

        public IActionResult Index()
        {
            if (User.IsInRole("CanManageMovies"))
                return View("Lists");

            return View("ReadOnlyLists");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = _context.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);

            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


    }
}

Vidly/Vidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Vidly.Data;
using Vidly.Models;
using Vidly.ViewModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Authorization;

namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieRentDbContext _context;

        public MoviesController(MovieRentDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpGet]
        public ActionResult Save()
        {
            var genres = _context.Genres.ToList();

            var model = new SaveMovieViewModel()
            {
                Genres = genres
            };
            return View(model);
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(Movie movie)
        {
            if (ModelState.IsValid)
            {
                if (movie.Id == 0)
                {
                    movie.DateAdded = DateTime.Now;
                    _context.Movies.Add(movie);
                }
                else
                {
                    var existingMovie = _context.Movies.FirstOrDefault(m => m.Id == movie.Id);
                    existingMovie.Name = movie.Name;
                    existingMovie.GenreId = movie.GenreId;
                    existingMovie.ReleaseDate = movie.ReleaseDate;
                    existingMovie.Stock = movie.Stock;
                }

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            var viewModel = new SaveMovieViewModel(movie)
            {
                Genres = _context.Genres.ToList()
            };
            return View(viewModel);
        }

        [Authorize(Roles = "CanManageMovies")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);

            if (movie == null)
            {
                return NotFound();
            }

            var viewModel = new SaveMovieViewModel(movie)
            {
                Genres = _context.Genres.ToList()
            };

            return View("Save", viewModel);
        }
       
        public IActionResult Index()
        {
            if(User.IsInRole("CanManageMovies"))
                return View("Lists");

            return View("ReadOnlyLists");
        }


        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = _context.Movies.Include(m => m.Genre).FirstOrDefault(m => m.Id == id);

            return View(movie);
        }

        public IActionResult Random(int id)
        {
            Movie movie = new Movie
            {
                Id = 101,
                Name = "Shrek!"
            };
            var customers = new List<Customer>
            {
                new Customer{Name = "Customer 1"},
                new Customer{Name = "Customer 2"}
            };
            var viewModel = new RandomMovieViewModel
            {
                Movie = movie,
                Customers = customers
            };
            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

    }
}

Vidly/Vidly/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vidly.Controllers
{
    public class RentalsController : Controller
    {
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
    }
}

Vidly/Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/css/typeahead.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vidly</a>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @*LoginPartial*@
                    <partial name="_LoginPartial"/>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="New">New Rental</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>

           
          

        </nav>
        
           
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Vidly - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/typeahead.js/typeahead.bundle.js"></script>
    <script src="~/lib/bootbox.js/bootbox.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>